# Generated by Django 5.0.3 on 2024-03-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_mon_hoc', models.CharField(default='000000', max_length=10)),
                ('ten_mon_hoc', models.CharField(default='000000', max_length=50)),
                ('so_TC', models.IntegerField(default=0)),
                ('giang_vien', models.CharField(default='null', max_length=100)),
                ('so_danh_gia', models.IntegerField(default=0)),
            ],
        ),
    ]
