# Generated by Django 5.0.3 on 2024-03-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_item_id_alter_item_ma_mon_hoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='binh_luan',
            field=models.TextField(default=''),
        ),
    ]
