# Generated by Django 5.0.3 on 2024-03-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_item_binh_luan_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='giang_vien',
            field=models.CharField(default='Giảng viên mới', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='ten_mon_hoc',
            field=models.CharField(default='Môn học mới', max_length=50),
        ),
    ]
