# Generated by Django 5.0.3 on 2024-03-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_item_giang_vien_alter_item_ten_mon_hoc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='so_danh_gia',
        ),
        migrations.AddField(
            model_name='comment',
            name='so_danh_gia',
            field=models.IntegerField(default=0),
        ),
    ]
