# Generated by Django 5.0.3 on 2024-03-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_item_so_danh_gia_comment_so_danh_gia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='so_danh_gia',
        ),
        migrations.AddField(
            model_name='item',
            name='so_danh_gia',
            field=models.IntegerField(default=0),
        ),
    ]
